services:
    shobar_wp:
        build:
          context: ./wp
        container_name: shobar_wp
        restart: always
        ports:
            - 4444:80
        depends_on:
            - shobar_db
        volumes:
            - ./wp/src:/var/www/html
        environment:
            WORDPRESS_DB_HOST: shobar_db
            WORDPRESS_DB_USER: serhii
            WORDPRESS_DB_PASSWORD: 111111
            WORDPRESS_DB_NAME: shobar
            WORDPRESS_DEBUG: 1

    shobar_db:
        image: mysql:8.0
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        container_name: shobar_db
        restart: always
        ports:
          - 2217:3306
        volumes:
            - ./db/storage:/var/lib/mysql
        environment:
            MYSQL_DATABASE: shobar
            MYSQL_USER: serhii
            MYSQL_PASSWORD: 111111
            MYSQL_ROOT_PASSWORD: 111111
